### ISSUE TITLE
Feature Request: Add translation system

### ISSUE THREAD

**Issue by erunks** [leaderboardsgg/leaderboard-site#149]
### What are you wanting to be added?

We should add a translation system as early as possible, for easier integration later on. Probably will want to utilize this package, https://www.npmjs.com/package/@nuxtjs/i18n, as it looks really promising.

For acceptance, this should just move basic text snippets like: `login`, `sign up`, etc. to a translation file for English and have it render properly.

### What might break?

Nothing should 🤞 

### Relevant Issues

N/A

**Comment by legrandgrand** [comment]
On that note, design-wise: 

- create the translation json(s) separatly from the init i18n setup.
- A **folder** for each languages translated, in which the jsons will be
- Every translations should be split by component (one JSON block for the header, one for login, etc.) for better maintainability
- Finally, don't put all the translations in the same file; try to split the files so that they stay readable and maintainable. This will require a mapping function to get the "full" JSON at runtime

**Comment by legrandgrand** [comment]
Feedback from @just-ero : 
* If the translation isn't available in language X, default to English

**Comment by zysim** [comment]
Do we have a separate repo for the translations?
