### ISSUE TITLE
Bug: Closing the tab logs you out

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-site#590]
### What happened?

While logged into the website, upon closing the tab where I was logged in, I was no longer logged in.

### What did you expect to happen?

Closing the tab where I am logged into the website and then re-opening it (while keeping the browser open) should not affect my login state.

### Step(s) to Reproduce

Open two browser tabs. In one tab, log into the website. Close that tab. Navigate to the website. You are no longer logged in.

### Were you on mobile when this happened?

No

### What browsers are you seeing the problem on?

Firefox

**Comment by erunks** [comment]
Some extra context here for whoever picks this up, the reason why this is happening currently is because we're just storing the current user and their session token in a global `nuxt` state. If we move this to something like `localStorage` then this should be resolved. These states are defined in the [`useCurrentUser`](https://github.com/leaderboardsgg/leaderboard-site/blob/main/composables/useCurrentUser.ts) and [`useSessionToken`](https://github.com/leaderboardsgg/leaderboard-site/blob/main/composables/useSessionToken.ts) composables.

**Comment by TheTedder** [comment]
I have successfully made the site use cookies to store the current user and session on my branch [here](https://github.com/TheTedder/leaderboard-site/tree/persistent-login) but I have somehow broken the tests in the process. Reassigning this task to @buffet-time who volunteered to fix them.
